created serach/app bar
Classy-Bear/oshin-list pull request #6
Opened 2021-11-11 19:40 UTC by jose-oshin

2021-11-11 23:59 UTC, david-oshin commented on lib/core/widgets/serch_app_bar/search_app_bar.dart
> +  /// Creates the AppBar with the search, is necesary tu call it inside of a [PreferredSize] widget
Porfavor al menos usar el traductor.

2021-11-12 01:07 UTC, david-oshin requested changes
* Hacer `flutter format` al terminar.
* [Usar clases en vez de funciones](https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-reusable-widgets) en Widgets.

2021-11-12 01:07 UTC, david-oshin commented on lib/core/widgets/serch_app_bar/search_app_bar.dart
> +            borderSide: BorderSide(color: Colors.blue)),
Trailing comma en la línea 44

2021-11-12 01:07 UTC, david-oshin commented on lib/core/widgets/serch_app_bar/search_app_bar.dart
> +        )),
Trailing comma en la línea 50

2021-11-12 01:07 UTC, david-oshin commented on lib/core/widgets/filter_chips/filter_chips.dart
> +    required this.onFilterSelect
Trailing comma en la línea 12

2021-11-12 01:07 UTC, david-oshin commented on lib/core/widgets/filter_chips/filter_chips.dart
> +              children: stringToChips()
Trailing comma en la línea 29

2021-11-12 01:07 UTC, david-oshin commented on lib/core/widgets/filter_chips/filter_chips.dart
> +}
Agrega una nueva línea a la 67

2021-11-12 15:42 UTC, jose-oshin commented
ya realicé los cambios requeridos

2021-11-12 15:56 UTC, david-oshin approved these changes

2021-11-12 15:56 UTC, merged